name: maven-verify

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Generate Maven Settings
        uses: whelk-io/maven-settings-xml-action@v18
        with:
          repositories: >
            [
              {
                "id": "oss.sonatype.org",
                "name": "sonatype public nexus",
                "url": "https://s01.oss.sonatype.org/content/groups/public"
              }
            ]
          plugin_repositories: >
            [
              {
                "id": "oss.sonatype.org",
                "name": "sonatype public nexus",
                "url": "https://s01.oss.sonatype.org/content/groups/public"
              }
            ]
          servers: >
            [
              {
                "id": "github",
                "username": "${env.GITHUB_ACTOR}",
                "password": "${env.GITHUB_TOKEN}"
              },
              {
                "id": "ossrh",
                "username": "${{ secrets.OSS_USERNAME }}",
                "password": "${{ secrets.OSS_PASSWORD }}"
              }
            ]

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Deploy with Maven
        run: mvn --batch-mode --update-snapshots clean deploy